### ISSUE TITLE
Adding kubernetes_limit_range caused Terraform to crash

### ISSUE THREAD

**Issue by phsys** [hashicorp/terraform-provider-kubernetes#1498]
### Terraform Version, Provider Version and Kubernetes Version
```
Terraform version: v1.0.10
Kubernetes provider version: v2.6.1
Kubernetes version: 1.19.11
```

### Affected Resource(s)
Kubernetes Namespace. Kubernetes Limit Range should get applied to every namespace. But Terraform crashes if we include the kubernetes_limit_range resource.

### Terraform Configuration Files
Snippet of the relevant portion from Terraform configuration file
```hcl
resource "kubernetes_namespace" "namespace" {
  metadata {
    name = var.name

    annotations = merge({
      "app.kubernetes.io/managed-by" = "Terraform"
    }, var.annotations)

    labels = merge({}, var.labels)

  }
}

resource "kubernetes_resource_quota" "quota" {
  metadata {
    name      = var.name
    namespace = var.name

    annotations = {
      "app.kubernetes.io/managed-by" = "Terraform"
    }
  }

  spec {
    hard   = var.quota_limits
  }
}

resource "kubernetes_limit_range" "limit-range" {
  metadata {
    name      = var.name
    namespace = var.name

    annotations = {
      "app.kubernetes.io/managed-by" = "Terraform"
    }
  }

  spec {
    limit {
      type            = "Container"
      default         = var.limitrange_limits
      default_request = var.limitrange_requests
    }
  }
}

```

### Panic Output

Main highlight: `interface conversion: interface {} is nil, not map[string]interface {}`

Snippet:
```
Stack trace from the terraform-provider-kubernetes_v2.6.1_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 194 [running]:
github.com/hashicorp/terraform-provider-kubernetes/kubernetes.expandResourceQuotaSpec(0xc0011bffc0, 0x1, 0x1, 0x1f21ae0, 0xc0016861e0, 0x1)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/kubernetes/structures.go:318 +0x31f
github.com/hashicorp/terraform-provider-kubernetes/kubernetes.resourceKubernetesResourceQuotaCreate(0x26998b8, 0xc0011bc7e0, 0xc00119a580, 0x21bd400, 0xc001061f40, 0xc0011bfa30, 0xb0e3ea, 0xc0013e2d80)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/kubernetes/resource_kubernetes_resource_quota.go:114 +0x21d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00013f7a0, 0x2699848, 0xc0013cef40, 0xc00119a580, 0x21bd400, 0xc001061f40, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:330 +0x17f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00013f7a0, 0x2699848, 0xc0013cef40, 0xc001312230, 0xc0013e2d80, 0x21bd400, 0xc001061f40, 0x0, 0x0, 0x0, ...)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:456 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0006b4468, 0x2699848, 0xc0013cef40, 0xc0013d6b90, 0xc000ed29b8, 0x1, 0x30)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-mux.SchemaServer.ApplyResourceChange(0xc000ed9710, 0xc000ed9740, 0xc0011d6520, 0x2, 0x2, 0xc0001d6600, 0x1, 0x2699848, 0xc0013cef40, 0xc0013d6b90, ...)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform-plugin-mux/schema_server.go:287 +0x98
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc0011d6540, 0x26998f0, 0xc0013cef40, 0xc001312000, 0xc0011d6540, 0xc00130a8a0, 0xc000b96ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x220b4e0, 0xc0011d6540, 0x26998f0, 0xc00130a8a0, 0xc0013dd260, 0x0, 0x26998f0, 0xc00130a8a0, 0xc001310000, 0x240)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000252c40, 0x26b14b8, 0xc000702f00, 0xc0018e3320, 0xc000ed97d0, 0x351bb00, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/vendor/google.golang.org/grpc/server.go:1217 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000252c40, 0x26b14b8, 0xc000702f00, 0xc0018e3320, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/vendor/google.golang.org/grpc/server.go:1540 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00011c2e0, 0xc000252c40, 0x26b14b8, 0xc000702f00, 0xc0018e3320)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/vendor/google.golang.org/grpc/server.go:878 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/vendor/google.golang.org/grpc/server.go:876 +0x1fd
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 259 [running]:
github.com/hashicorp/terraform-provider-kubernetes/kubernetes.expandResourceQuotaSpec(0xc0015d06f0, 0x1, 0x1, 0x1f21ae0, 0xc001a77098, 0x1)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/kubernetes/structures.go:318 +0x31f
github.com/hashicorp/terraform-provider-kubernetes/kubernetes.resourceKubernetesResourceQuotaCreate(0x26998b8, 0xc001594ba0, 0xc001584400, 0x21bd400, 0xc001061f40, 0xc0015d0200, 0xb0e3ea, 0xc00150c680)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/kubernetes/resource_kubernetes_resource_quota.go:114 +0x21d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00013f7a0, 0x2699848, 0xc001504700, 0xc001584400, 0x21bd400, 0xc001061f40, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:330 +0x17f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00013f7a0, 0x2699848, 0xc001504700, 0xc001590460, 0xc00150c680, 0x21bd400, 0xc001061f40, 0x0, 0x0, 0x0, ...)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:456 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0006b4468, 0x2699848, 0xc001504700, 0xc001500410, 0xc000ed29b8, 0xc001a78d01, 0x30)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-mux.SchemaServer.ApplyResourceChange(0xc000ed9710, 0xc000ed9740, 0xc0011d6520, 0x2, 0x2, 0xc0001d6600, 0x1, 0x2699848, 0xc001504700, 0xc001500410, ...)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform-plugin-mux/schema_server.go:287 +0x98
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc0011d6540, 0x26998f0, 0xc001504700, 0xc001590310, 0xc0011d6540, 0xc000b92ba0, 0x46cdc7)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x220b4e0, 0xc0011d6540, 0x26998f0, 0xc001a78cf0, 0xc0015944e0, 0x0, 0x26998f0, 0xc001a78cf0, 0xc0015b0480, 0x234)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000252c40, 0x26b14b8, 0xc000702f00, 0xc001a7b680, 0xc000ed97d0, 0x351bb00, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/vendor/google.golang.org/grpc/server.go:1217 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000252c40, 0x26b14b8, 0xc000702f00, 0xc001a7b680, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/vendor/google.golang.org/grpc/server.go:1540 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00011c2e0, 0xc000252c40, 0x26b14b8, 0xc000702f00, 0xc001a7b680)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/vendor/google.golang.org/grpc/server.go:878 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/vendor/google.golang.org/grpc/server.go:876 +0x1fd

Error: The terraform-provider-kubernetes_v2.6.1_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Steps to Reproduce
<!-- Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Expected Behavior
Kubernetes Limit Range should get applied to every namespace. 

### Actual Behavior
Terraform crashes if we include the kubernetes_limit_range resource.

### Important Factoids
Kubernetes is running on premises.

### References
The panic error is similar as in https://github.com/hashicorp/terraform-provider-kubernetes/issues/1476, but the cause seems to be different.

**Comment by iBrandyJackson** [comment]
This issue should now be resolved. If you continue to run into this issue, or if you have found a problem that seems related to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further. This helps our maintainers find and focus on the active issues. Thanks!
