### ISSUE TITLE
kubernetes_manifest stack trace when planning

### ISSUE THREAD

**Issue by zhangluva** [hashicorp/terraform-provider-kubernetes#1649]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 1.1.7
Kubernetes provider version: 2.8.0_x5
Kubernetes version: 1.21
```

### Affected Resource(s)

kubernetes_manifest

### Terraform Configuration Files
```hcl
resource "kubernetes_manifest" "this" {
  manifest = {
    "apiVersion" = "kafka.strimzi.io/v1beta2"
    "kind" = "Kafka"
    "metadata" = {
      "name" = "${var.cluster_name}"
      "namespace" = "${var.namespace}"
    }
    "spec" = {
      "kafka" = {
          "listeners" = [
          {
            "name" = "plain"
            "port" = 9092
            "tls" = false
            "type" = "internal"
          },
          {
            "authentication" = {
              "type" = "tls"
            }
            "name" = "tls"
            "port" = 9093
            "tls" = true
            "type" = "internal"
          },
          {
            "name" = "external"
            "port" = "9094"
            "tls"  = false
            "type" = "loadbalancer"
            "configuration" = {
              "brokers" = [
                for idx in range(var.broker-replicas):
                  {
                    "broker" = idx
                  }
              ]
            }
          }
        ]
      }
    }
  }
}
```

### Debug Output

https://gist.github.com/zhangluva/15130df23de3a92757c09cc47b530ef5
### Panic Output

```
╷
│ Error: Plugin did not respond
│
│   with module.staging.kubernetes_manifest.this,
│   on ../module/main.tf line 1, in resource "kubernetes_manifest" "this":
│    1: resource "kubernetes_manifest" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).PlanResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-kubernetes_v2.8.0_x5 plugin:

panic: ElementKeyInt(2): can't use tftypes.Object["authentication":tftypes.Object["accessTokenIsJwt":tftypes.Bool, "checkAccessTokenType":tftypes.Bool, "checkAudience":tftypes.Bool, "checkIssuer":tftypes.Bool, "clientAudience":tftypes.String, "clientId":tftypes.String, "clientScope":tftypes.String, "clientSecret":tftypes.Object["key":tftypes.String, "secretName":tftypes.String], "connectTimeoutSeconds":tftypes.Number, "customClaimCheck":tftypes.String, "disableTlsHostnameVerification":tftypes.Bool, "enableECDSA":tftypes.Bool, "enableOauthBearer":tftypes.Bool, "enablePlain":tftypes.Bool, "fallbackUserNameClaim":tftypes.String, "fallbackUserNamePrefix":tftypes.String, "groupsClaim":tftypes.String, "groupsClaimDelimiter":tftypes.String, "introspectionEndpointUri":tftypes.String, "jwksEndpointUri":tftypes.String, "jwksExpirySeconds":tftypes.Number, "jwksMinRefreshPauseSeconds":tftypes.Number, "jwksRefreshSeconds":tftypes.Number, "listenerConfig":tftypes.DynamicPseudoType, "maxSecondsWithoutReauthentication":tftypes.Number, "readTimeoutSeconds":tftypes.Number, "sasl":tftypes.Bool, "secrets":tftypes.List[tftypes.Object["key":tftypes.String, "secretName":tftypes.String]], "tlsTrustedCertificates":tftypes.List[tftypes.Object["certificate":tftypes.String, "secretName":tftypes.String]], "tokenEndpointUri":tftypes.String, "type":tftypes.String, "userInfoEndpointUri":tftypes.String, "userNameClaim":tftypes.String, "validIssuerUri":tftypes.String, "validTokenType":tftypes.String], "configuration":tftypes.Object["bootstrap":tftypes.Object["alternativeNames":tftypes.List[tftypes.String], "annotations":tftypes.DynamicPseudoType, "host":tftypes.String, "labels":tftypes.DynamicPseudoType, "loadBalancerIP":tftypes.String, "nodePort":tftypes.Number], "brokerCertChainAndKey":tftypes.Object["certificate":tftypes.String, "key":tftypes.String, "secretName":tftypes.String], "brokers":tftypes.Tuple[tftypes.Object["advertisedHost":tftypes.String, "advertisedPort":tftypes.Number, "annotations":tftypes.DynamicPseudoType, "broker":tftypes.Number, "host":tftypes.String, "labels":tftypes.DynamicPseudoType, "loadBalancerIP":tftypes.String, "nodePort":tftypes.Number], tftypes.Object["advertisedHost":tftypes.String, "advertisedPort":tftypes.Number, "annotations":tftypes.DynamicPseudoType, "broker":tftypes.Number, "host":tftypes.String, "labels":tftypes.DynamicPseudoType, "loadBalancerIP":tftypes.String, "nodePort":tftypes.Number], tftypes.Object["advertisedHost":tftypes.String, "advertisedPort":tftypes.Number, "annotations":tftypes.DynamicPseudoType, "broker":tftypes.Number, "host":tftypes.String, "labels":tftypes.DynamicPseudoType, "loadBalancerIP":tftypes.String, "nodePort":tftypes.Number]], "class":tftypes.String, "createBootstrapService":tftypes.Bool, "externalTrafficPolicy":tftypes.String, "finalizers":tftypes.List[tftypes.String], "ipFamilies":tftypes.List[tftypes.String], "ipFamilyPolicy":tftypes.String, "loadBalancerSourceRanges":tftypes.List[tftypes.String], "maxConnectionCreationRate":tftypes.Number, "maxConnections":tftypes.Number, "preferredNodePortAddressType":tftypes.String, "useServiceDnsDomain":tftypes.Bool], "name":tftypes.String, "networkPolicyPeers":tftypes.Tuple[tftypes.Object["ipBlock":tftypes.Object["cidr":tftypes.String, "except":tftypes.List[tftypes.String]], "namespaceSelector":tftypes.Object["matchExpressions":tftypes.List[tftypes.Object["key":tftypes.String, "operator":tftypes.String, "values":tftypes.List[tftypes.String]]], "matchLabels":tftypes.DynamicPseudoType], "podSelector":tftypes.Object["matchExpressions":tftypes.List[tftypes.Object["key":tftypes.String, "operator":tftypes.String, "values":tftypes.List[tftypes.String]]], "matchLabels":tftypes.DynamicPseudoType]]], "port":tftypes.Number, "tls":tftypes.Bool, "type":tftypes.String] as tftypes.Object["authentication":tftypes.Object["accessTokenIsJwt":tftypes.Bool, "checkAccessTokenType":tftypes.Bool, "checkAudience":tftypes.Bool, "checkIssuer":tftypes.Bool, "clientAudience":tftypes.String, "clientId":tftypes.String, "clientScope":tftypes.String, "clientSecret":tftypes.Object["key":tftypes.String, "secretName":tftypes.String], "connectTimeoutSeconds":tftypes.Number, "customClaimCheck":tftypes.String, "disableTlsHostnameVerification":tftypes.Bool, "enableECDSA":tftypes.Bool, "enableOauthBearer":tftypes.Bool, "enablePlain":tftypes.Bool, "fallbackUserNameClaim":tftypes.String, "fallbackUserNamePrefix":tftypes.String, "groupsClaim":tftypes.String, "groupsClaimDelimiter":tftypes.String, "introspectionEndpointUri":tftypes.String, "jwksEndpointUri":tftypes.String, "jwksExpirySeconds":tftypes.Number, "jwksMinRefreshPauseSeconds":tftypes.Number, "jwksRefreshSeconds":tftypes.Number, "listenerConfig":tftypes.DynamicPseudoType, "maxSecondsWithoutReauthentication":tftypes.Number, "readTimeoutSeconds":tftypes.Number, "sasl":tftypes.Bool, "secrets":tftypes.List[tftypes.Object["key":tftypes.String, "secretName":tftypes.String]], "tlsTrustedCertificates":tftypes.List[tftypes.Object["certificate":tftypes.String, "secretName":tftypes.String]], "tokenEndpointUri":tftypes.String, "type":tftypes.String, "userInfoEndpointUri":tftypes.String, "userNameClaim":tftypes.String, "validIssuerUri":tftypes.String, "validTokenType":tftypes.String], "configuration":tftypes.Object["bootstrap":tftypes.Object["alternativeNames":tftypes.List[tftypes.String], "annotations":tftypes.DynamicPseudoType, "host":tftypes.String, "labels":tftypes.DynamicPseudoType, "loadBalancerIP":tftypes.String, "nodePort":tftypes.Number], "brokerCertChainAndKey":tftypes.Object["certificate":tftypes.String, "key":tftypes.String, "secretName":tftypes.String], "brokers":tftypes.Tuple[tftypes.Object["advertisedHost":tftypes.String, "advertisedPort":tftypes.Number, "annotations":tftypes.DynamicPseudoType, "broker":tftypes.Number, "host":tftypes.String, "labels":tftypes.DynamicPseudoType, "loadBalancerIP":tftypes.String, "nodePort":tftypes.Number]], "class":tftypes.String, "createBootstrapService":tftypes.Bool, "externalTrafficPolicy":tftypes.String, "finalizers":tftypes.List[tftypes.String], "ipFamilies":tftypes.List[tftypes.String], "ipFamilyPolicy":tftypes.String, "loadBalancerSourceRanges":tftypes.List[tftypes.String], "maxConnectionCreationRate":tftypes.Number, "maxConnections":tftypes.Number, "preferredNodePortAddressType":tftypes.String, "useServiceDnsDomain":tftypes.Bool], "name":tftypes.String, "networkPolicyPeers":tftypes.Tuple[tftypes.Object["ipBlock":tftypes.Object["cidr":tftypes.String, "except":tftypes.List[tftypes.String]], "namespaceSelector":tftypes.Object["matchExpressions":tftypes.List[tftypes.Object["key":tftypes.String, "operator":tftypes.String, "values":tftypes.List[tftypes.String]]], "matchLabels":tftypes.DynamicPseudoType], "podSelector":tftypes.Object["matchExpressions":tftypes.List[tftypes.Object["key":tftypes.String, "operator":tftypes.String, "values":tftypes.List[tftypes.String]]], "matchLabels":tftypes.DynamicPseudoType]]], "port":tftypes.Number, "tls":tftypes.Bool, "type":tftypes.String]

goroutine 43 [running]:
github.com/hashicorp/terraform-plugin-go/tftypes.NewValue(...)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform-plugin-go/tftypes/value.go:277
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.morphTupleIntoType(0x2fe9888, 0xc00136d890, 0x2960860, 0xc000434d98, 0x2fe9888, 0xc0017bc5d0, 0xc001709440, 0x28, 0x203000, 0x203000, ...)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/morph.go:190 +0x1bb9
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.ValueToType(0x2fe9888, 0xc00136d890, 0x2960860, 0xc000434d98, 0x2fe9888, 0xc0017bc5d0, 0xc001709440, 0x4, 0xc00341eb40, 0x2c03fe0, ...)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/morph.go:30 +0xa09
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.morphObjectToType(0x2fe97e8, 0xc00136dbc0, 0x2a60e60, 0xc00131ca50, 0x2fe97e8, 0xc0017bc600, 0xc001709410, 0x1100000000000188, 0x203000, 0x203000, ...)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/morph.go:314 +0x425
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.ValueToType(0x2fe97e8, 0xc00136dbc0, 0x2a60e60, 0xc00131ca50, 0x2fe97e8, 0xc0017bc600, 0xc001709410, 0x2, 0x0, 0x0, ...)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/morph.go:36 +0x709
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.morphObjectToType(0x2fe97e8, 0xc00136df20, 0x2a60e60, 0xc00131c810, 0x2fe97e8, 0xc0032ea330, 0xc0017093f8, 0x1100000002fe97e8, 0xc00341eb40, 0x2a60e60, ...)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/morph.go:314 +0x425
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.ValueToType(0x2fe97e8, 0xc00136df20, 0x2a60e60, 0xc00131c810, 0x2fe97e8, 0xc0032ea330, 0xc0017093f8, 0x1, 0xc00341eb40, 0x2a60e60, ...)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/morph.go:36 +0x709
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.morphObjectToType(0x2fe97e8, 0xc00137c300, 0x2a60e60, 0xc001301da0, 0x2fe97e8, 0xc00341e270, 0xc0017092d8, 0x1100000000000010, 0xc0035c73b0, 0x8, ...)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/morph.go:314 +0x425
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.ValueToType(0x2fe97e8, 0xc00137c300, 0x2a60e60, 0xc001301da0, 0x2fe97e8, 0xc00341e270, 0xc0017092d8, 0x2, 0x5, 0x0, ...)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/morph.go:36 +0x709
github.com/hashicorp/terraform-provider-kubernetes/manifest/provider.(*RawProviderServer).PlanResourceChange(0xc001448200, 0x2fd6cf8, 0xc001040c00, 0xc0012d4460, 0xc00041fe08, 0xc000e18701, 0x1)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/manifest/provider/plan.go:315 +0x1cbb
github.com/hashicorp/terraform-plugin-mux.SchemaServer.PlanResourceChange(0xc0005a04b0, 0xc0005a04e0, 0xc000f96ae0, 0x2, 0x2, 0xc001448100, 0x1, 0x2fd6cf8, 0xc001040c00, 0xc0012d4460, ...)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform-plugin-mux/schema_server.go:276 +0x98
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).PlanResourceChange(0xc00045c000, 0x2fd6da0, 0xc0012dac60, 0xc001bfc000, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:777 +0x7f0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler(0x2c1d160, 0xc00045c000, 0x2fd6da0, 0xc0012dac60, 0xc0000a07e0, 0x0, 0x2fd6da0, 0xc0012dac60, 0xc00035e800, 0x7cb)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:367 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000222a80, 0x2fed818, 0xc0011f81a0, 0xc001505440, 0xc0005a05a0, 0x3d93a68, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/vendor/google.golang.org/grpc/server.go:1282 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000222a80, 0x2fed818, 0xc0011f81a0, 0xc001505440, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/vendor/google.golang.org/grpc/server.go:1616 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0004f5620, 0xc000222a80, 0x2fed818, 0xc0011f81a0, 0xc001505440)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/vendor/google.golang.org/grpc/server.go:921 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-kubernetes/vendor/google.golang.org/grpc/server.go:919 +0x1fd

Error: The terraform-provider-kubernetes_v2.8.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```
### Steps to Reproduce

1. `terraform init`
2. `terraform plan` 
### Expected Behavior
What should have happened?
Successfully generate plan
### Actual Behavior
What actually happened?
Stack trace
### Important Factoids

Same config works fine if set kubernetes provider to version 2.7.1. It would stack trace when using `>=. 2.7.1`
```
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "= 2.7.1"
    }
```
### References

- GH-1234

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tungtt1006** [comment]
Same error here, same StrimziKafka.
