### ISSUE TITLE
Provider crashes on PrometheusRules with multiple alerts defined 

### ISSUE THREAD

**Issue by diseku** [hashicorp/terraform-provider-kubernetes#1737]
A valid PrometheusRule with multiple alert rules defined is resulting in provider crash on plan.
Applying just one alert rule per group works fine. 

### Terraform Version, Provider Version and Kubernetes Version
```
Terraform version: 1.1.7, 1.2.2
Kubernetes provider version: 2.11.0
Kubernetes version: 1.21
```

### Affected Resource(s)
`kubernetes_manifest`

### Terraform Configuration Files
```hcl
resource "kubernetes_manifest" "resource_test" {
  manifest = {
    apiVersion = "monitoring.coreos.com/v1"
    kind       = "PrometheusRule"
    metadata = {
      labels = {
        alerting   = "enabled"
        prometheus = "server"
        role       = "alert-rules"
      }
      name      = "test-rules"
      namespace = "qa"
    }
    spec = {
      groups = [
        {
          name = "test"
          rules = [
            {
              alert = "one"
              annotations = {
                description = "nope"
                summary     = "nope"
              }
              expr = "some_metric_name > 10"
              for  = "5m"
            },
            {
              alert = "two"
              annotations = {
                description = "nope"
                summary     = "nope"
              }
              expr = "some_metric_name > 10"
              for  = "5m"
            }
          ]
        }
      ]
    }
  }
}
```

### Debug Output
[debug.gist](https://gist.github.com/diseku/0148d7815fb363681656c5e1e5a187aa)

### Panic Output
```sh
╷
│ Error: Plugin did not respond
│ 
│   with kubernetes_manifest.resource_test,
│   on main.tf line 113, in resource "kubernetes_manifest" "resource_test":
│  113: resource "kubernetes_manifest" "resource_test" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).PlanResourceChange call. The
│ plugin logs may contain more details.
╵

Stack trace from the terraform-provider-kubernetes_v2.11.0_x5 plugin:

panic: ElementKeyInt(0): can't use tftypes.Object["interval":tftypes.String, "name":tftypes.String, "rules":tftypes.Tuple[tftypes.Object["alert":tftypes.String, "annotations":tftypes.DynamicPseudoType, "expr":tftypes.DynamicPseudoType, "for":tftypes.String, "labels":tftypes.DynamicPseudoType, "record":tftypes.String], tftypes.Object["alert":tftypes.String, "annotations":tftypes.DynamicPseudoType, "expr":tftypes.DynamicPseudoType, "for":tftypes.String, "labels":tftypes.DynamicPseudoType, "record":tftypes.String]]] as tftypes.Object["interval":tftypes.String, "name":tftypes.String, "rules":tftypes.Tuple[tftypes.Object["alert":tftypes.String, "annotations":tftypes.DynamicPseudoType, "expr":tftypes.DynamicPseudoType, "for":tftypes.String, "labels":tftypes.DynamicPseudoType, "record":tftypes.String]]]

goroutine 146 [running]:
github.com/hashicorp/terraform-plugin-go/tftypes.NewValue(...)
	github.com/hashicorp/terraform-plugin-go@v0.8.0/tftypes/value.go:277
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.morphTupleIntoType({{0x2083708?, 0xc000fe4750?}, {0x1a0be40?, 0xc00061c918?}}, {0x2083708?, 0xc002ddf680?}, 0xc000ed3f68)
	github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/morph.go:190 +0x1098
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.ValueToType({{0x2083708?, 0xc000fe4750?}, {0x1a0be40?, 0xc00061c918?}}, {0x2083708, 0xc002ddf680}, 0x1c94060?)
	github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/morph.go:30 +0x5f5
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.morphObjectToType({{0x2083668?, 0xc000fe56b0?}, {0x1b0e860?, 0xc000fb31a0?}}, {0x2083668?, 0xc002ddf6b0?}, 0xc000ed3f08)
	github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/morph.go:314 +0xb85
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.ValueToType({{0x2083668?, 0xc000fe56b0?}, {0x1b0e860?, 0xc000fb31a0?}}, {0x2083668, 0xc002ddf6b0}, 0x1891635?)
	github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/morph.go:36 +0x4a5
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.morphObjectToType({{0x2083668?, 0xc000fe9260?}, {0x1b0e860?, 0xc000faef30?}}, {0x2083668?, 0xc002e3b320?}, 0xc000ed3d10)
	github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/morph.go:314 +0xb85
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.ValueToType({{0x2083668?, 0xc000fe9260?}, {0x1b0e860?, 0xc000faef30?}}, {0x2083668, 0xc002e3b320}, 0xc00139ec62?)
	github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/morph.go:36 +0x4a5
github.com/hashicorp/terraform-provider-kubernetes/manifest/provider.(*RawProviderServer).PlanResourceChange(0xc0006a3800, {0x2080160, 0xc000e8e690}, 0xc0004e8b40)
	github.com/hashicorp/terraform-provider-kubernetes/manifest/provider/plan.go:327 +0x313b
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.PlanResourceChange({0xc000e199e0, 0xc000e19a40, {0xc000ff3c80, 0x2, 0x2}, 0xc000e19a10, 0xc000e5e020, 0xc000feb520, 0xc000e19a70}, {0x20800b8, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.6.0/tf5muxserver/mux_server_PlanResourceChange.go:27 +0x142
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).PlanResourceChange(0xc000476c80, {0x2080160?, 0xc000e75d70?}, 0xc0005de380)
	github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:779 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler({0x1cb7000?, 0xc000476c80}, {0x2080160, 0xc000e75d70}, 0xc00046b6e0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:367 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000623180, {0x2084158, 0xc00029aea0}, 0xc0008ce000, 0xc000f18c90, 0x2e6df68, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc000623180, {0x2084158, 0xc00029aea0}, 0xc0008ce000, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1619 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.45.0/server.go:919 +0x28a

Error: The terraform-provider-kubernetes_v2.11.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Expected Behavior
Smooth plan and apply

### Actual Behavior
Crash

### Important Factoids
- Applying just one rule per group works as expected
- CRD in use: https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/main/manifests/setup/0prometheusruleCustomResourceDefinition.yaml

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by diseku** [comment]
ok, thank you for checking @alexsomesan.

setup issue on our side: for the CRD creation we were using http data source and `banzaicloud/k8s` provider to apply, which surprisingly has not updated the `prometheusrules.monitoring.coreos.com` for quite some time, so the plugin crash was related to the outdated CRD.
