### ISSUE TITLE
panic: required attribute "preStop" not set

### ISSUE THREAD

**Issue by vmotso** [hashicorp/terraform-provider-kubernetes#1950]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version:  v1.3.5
Kubernetes provider version: v2.16.1
Kubernetes version: v1.22.15-gke.100
```

### Terraform Configuration Files
```hcl
locals {
  condition = false
  postStart = {
    exec = {
      command = ["bash", "-c", "echo postStart"]
    }
  }
  preStop = {
    exec = {
      command = ["bash", "-c", "echo preStop"]
    }
  }
}
resource "kubernetes_manifest" "deploy_foo" {
  manifest = {
    apiVersion = "apps/v1"
    kind       = "Deployment"
    metadata = {
      name      = "foo"
      namespace = "foo"
      labels = {
        "app" = "foo"
      }
    }
    spec = {
      selector = {
        matchLabels = {
          "app" = "foo"
        }
      }
      template = {
        metadata = {
          labels = {
            "app" = "foo"
          },
        }
        spec = {
          containers = [
            {
              name  = "foo"
              image = "busybox"
              lifecycle = local.condition ? {
                postStart = local.postStart
                preStop   = local.preStop
                } : {
                postStart = local.postStart
              }
            }
          ]
        }
      }
    }
  }
}
```

### Panic Output

```
Stack trace from the terraform-provider-kubernetes_v2.16.1_x5 plugin:

panic: can't create a tftypes.Value of type tftypes.Object["postStart":tftypes.Object["exec":tftypes.Object["command":tftypes.List[tftypes.String]], "httpGet":tftypes.Object["host":tftypes.String, "httpHeaders":tftypes.List[tftypes.Object["name":tftypes.String, "value":tftypes.String]], "path":tftypes.String, "port":tftypes.String, "scheme":tftypes.String], "tcpSocket":tftypes.Object["host":tftypes.String, "port":tftypes.String]], "preStop":tftypes.Object["exec":tftypes.Object["command":tftypes.List[tftypes.String]], "httpGet":tftypes.Object["host":tftypes.String, "httpHeaders":tftypes.List[tftypes.Object["name":tftypes.String, "value":tftypes.String]], "path":tftypes.String, "port":tftypes.String, "scheme":tftypes.String], "tcpSocket":tftypes.Object["host":tftypes.String, "port":tftypes.String]]], required attribute "preStop" not set

goroutine 43 [running]:
github.com/hashicorp/terraform-plugin-go/tftypes.NewValue(...)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tftypes/value.go:273
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.morphMapToType({{0x2cee5d0?, 0xc000cfea50?}, {0x275dd00?, 0xc000cab020?}}, {0x2cee628?, 0xc001d20d80?}, 0xc0016c93e0)
	github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/morph.go:542 +0x13a5
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.ValueToType({{0x2cee5d0?, 0xc000cfea50?}, {0x275dd00?, 0xc000cab020?}}, {0x2cee628, 0xc001d20d80}, 0xc0016c93e0)
	github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/morph.go:44 +0x6f9
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.morphObjectToType({{0x2cee628?, 0xc000cfed50?}, {0x275dd00?, 0xc000caadb0?}}, {0x2cee628?, 0xc001da6de0?}, 0xc0016c9380)
	github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/morph.go:605 +0x1079
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.ValueToType({{0x2cee628?, 0xc000cfed50?}, {0x275dd00?, 0xc000caadb0?}}, {0x2cee628, 0xc001da6de0}, 0xc0016c9380)
	github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/morph.go:46 +0x6b5
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.morphTupleIntoType({{0x2cee6d8?, 0xc000996ff0?}, {0x2658260?, 0xc000357ad0?}}, {0x2cee578?, 0xc001dd5dd0?}, 0xc0016c9338)
	github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/morph.go:344 +0x13c5
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.ValueToType({{0x2cee6d8?, 0xc000996ff0?}, {0x2658260?, 0xc000357ad0?}}, {0x2cee578, 0xc001dd5dd0}, 0xc0016c9338)
	github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/morph.go:40 +0x785
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.morphObjectToType({{0x2cee628?, 0xc000997260?}, {0x275dd00?, 0xc000caaa50?}}, {0x2cee628?, 0xc002857170?}, 0xc0016c9308)
	github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/morph.go:605 +0x1079
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.ValueToType({{0x2cee628?, 0xc000997260?}, {0x275dd00?, 0xc000caaa50?}}, {0x2cee628, 0xc002857170}, 0xc0016c9308)
	github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/morph.go:46 +0x6b5
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.morphObjectToType({{0x2cee628?, 0xc000997560?}, {0x275dd00?, 0xc000caa090?}}, {0x2cee628?, 0xc0028571a0?}, 0xc0016c9248)
	github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/morph.go:605 +0x1079
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.ValueToType({{0x2cee628?, 0xc000997560?}, {0x275dd00?, 0xc000caa090?}}, {0x2cee628, 0xc0028571a0}, 0xc0016c9248)
	github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/morph.go:46 +0x6b5
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.morphObjectToType({{0x2cee628?, 0xc0009978f0?}, {0x275dd00?, 0xc000ab16e0?}}, {0x2cee628?, 0xc0028a68d0?}, 0xc0016c91a0)
	github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/morph.go:605 +0x1079
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.ValueToType({{0x2cee628?, 0xc0009978f0?}, {0x275dd00?, 0xc000ab16e0?}}, {0x2cee628, 0xc0028a68d0}, 0xc0016c91a0)
	github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/morph.go:46 +0x6b5
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.morphObjectToType({{0x2cee628?, 0xc000997d10?}, {0x275dd00?, 0xc0004d5e00?}}, {0x2cee628?, 0xc002afef90?}, 0xc0016c8fc0)
	github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/morph.go:605 +0x1079
github.com/hashicorp/terraform-provider-kubernetes/manifest/morph.ValueToType({{0x2cee628?, 0xc000997d10?}, {0x275dd00?, 0xc0004d5e00?}}, {0x2cee628, 0xc002afef90}, 0xc0016c8fc0)
	github.com/hashicorp/terraform-provider-kubernetes/manifest/morph/morph.go:46 +0x6b5
github.com/hashicorp/terraform-provider-kubernetes/manifest/provider.(*RawProviderServer).PlanResourceChange(0xc000f4c980, {0x2ce8a20, 0xc000dea960}, 0xc00069b540)
	github.com/hashicorp/terraform-provider-kubernetes/manifest/provider/plan.go:354 +0x3445
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.PlanResourceChange({0xc0010c46c0, 0xc0010c4720, {0xc0012caa20, 0x2, 0x2}, 0xc0010c46f0, 0xc0010ce090, 0xc001281610, 0xc0010c4750}, {0x2ce8a20, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.7.0/tf5muxserver/mux_server_PlanResourceChange.go:27 +0x142
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).PlanResourceChange(0xc000725a40, {0x2ce8a20?, 0xc000c321e0?}, 0xc0002b8070)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:783 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_PlanResourceChange_Handler({0x2909bc0?, 0xc000725a40}, {0x2ce8a20, 0xc000c321e0}, 0xc0002b8000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:367 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0008605a0, {0x2ceebb8, 0xc000348680}, 0xc001e10000, 0xc00137c060, 0x3b15948, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1295 +0xb2b
google.golang.org/grpc.(*Server).handleStream(0xc0008605a0, {0x2ceebb8, 0xc000348680}, 0xc001e10000, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1636 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-kubernetes_v2.16.1_x5 plugin crashed!
```

### Steps to Reproduce

```
# it works
lifecycle = {
  postStart = local.postStart
}

# it doesn't
lifecycle = false ? {
  postStart = local.postStart
  preStop   = local.preStop
  } : {
  postStart = local.postStart
}
```

### Expected Behavior
Possibility to have conditional lifecycle hooks(preStart, preStop).

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by BBBmau** [comment]
Thank you for opening this issue @vmotso, I started investigating and found that it happens also with `postStart` if we include `preStop` but leave out `postStart`

```
lifecycle = true ? {
                postStart = local.postStart
              } :{
                preStop = local.preStop
              }
```

I also tried with both true and false conditions with the top config which caused the same type of error. It could be because of the use of the conditional statement for the lifecycle value. I'll look into it more if theres a solution within the provider.

**Comment by jrhouston** [comment]
It seems like using the ternary operator creates some ambiguity about what type the `lifecycle` field should be. I guess because a ternary operator could return 2 completely different types depending on the conditional. If I don't use the ternary operator it appears as an type object, but with it the type comes out as a map. 

One possible workaround here is to shift the conditional to be inside the lifecycle object and use `null` as the else case. I don't seem to get the panic if I do this. 

```
lifecycle = {
  postStart = local.postStart
  preStop   = (local.condition) ? null : local.preStop
} 
```

**Comment by vmotso** [comment]
@jrhouston thanks for workaround! I thought about doing that before and got error in apply:
```
kubernetes_manifest.deploy_foo: Creating...
╷
│ Error: API response status: Failure
│
│   with kubernetes_manifest.deploy_foo,
│   on main.tf line 14, in resource "kubernetes_manifest" "deploy_foo":
│   14: resource "kubernetes_manifest" "deploy_foo" {
│
│ Deployment.apps "foo" is invalid: spec.template.spec.containers[0].lifecycle.preStop: Required value: must specify a handler type
╵
╷
│ Error: Kubernetes API Error: Invalid Deployment.apps [foo]
│
│   with kubernetes_manifest.deploy_foo,
│   on main.tf line 14, in resource "kubernetes_manifest" "deploy_foo":
│   14: resource "kubernetes_manifest" "deploy_foo" {
│
╵
╷
│ Error: spec.template.spec.containers[0].lifecycle.preStop
│
│   with kubernetes_manifest.deploy_foo,
│   on main.tf line 14, in resource "kubernetes_manifest" "deploy_foo":
│   14: resource "kubernetes_manifest" "deploy_foo" {
│
│ Required value: must specify a handler type
```

so as I see now, I can't optionaly deploy hooks

**Comment by BBBmau** [comment]
I'll be closing this issue since #2018 applies a diagnostic for certain cases such as this one.
